# frozen_string_literal: true

source 'https://rubygems.org'
gem 'bcrypt'
gem 'cinch'
gem 'cinch-authentication'
gem 'cinch-calculate'
gem 'cinch-convert'
gem 'cinch-cooldown'
gem 'cinch-dicebag'
gem 'cinch-evalso'
gem 'cinch-fortune'
gem 'cinch-isitup'
gem 'cinch-karma'
gem 'cinch-lastactive', git: 'https://github.com/bougyman/cinch-lastactive'
gem 'cinch-news'
gem 'cinch-seen'
gem 'cinch-urbandict'
gem 'cinch-weatherman'
gem 'cinch-wikipedia'
gem 'cleverbot', git: 'https://github.com/rubyists/cleverbot'
gem 'darksky_weather-api'
gem 'georuby'
gem 'htmlentities'
gem 'innate'
gem 'marky_markov'
gem 'mechanize'
gem 'nokogiri'
gem 'pg'
gem 'pg_array'
gem 'pry'
gem 'pry-remote'
gem 'rest-client'
gem 'rubocop'
gem 'sequel'
gem 'sequel-postgis-georuby'
gem 'sequel_postgresql_triggers'
gem 'timezone'
gem 'wolfram-alpha'
gem 'yt'
